In [4]:
import numpy as np

In [5]:
import numpy as np
Q1 = np.arange(10)

In [6]:
import numpy as np
Q2 = np.arange(10,50)
Q3 = Q2.copy()[::-1]

In [7]:
import numpy as np
Q4 = np.arange(1,10).reshape(3,3)

In [8]:
np.random.seed(42) 

Q5 = np.random.random(size = (10,5))

In [43]:
Q6A = np.min(Q5.round(4))

In [44]:
Q6B = np.max(Q5.round(4))

In [84]:
Q7 = round(Q5.mean(),4)

In [12]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Q8 = arr[0:10:2]

In [13]:
Q9 = arr.copy()
Q9[0:10:2] = 0

In [14]:
Q10 = np.where(Q9 % 2 != 0, -1, Q9)

In [60]:
Q11 = arr.reshape(2,5)
Q11

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [58]:
arr1 = np.arange(10).reshape((2,5))
arr2 = np.arange(10,20).reshape((2,5))

Q12 = np.vstack((arr1,arr2))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [17]:
Q13 = np.hstack((arr1,arr2))

In [18]:
arr3 = np.array([22,56,34,54,12,42,67,56,99]).reshape((3,3))

In [64]:
Q14 = arr3.copy()

Q14[:, [0, 1]] = Q14[:, [1, 0]]
Q14

array([[56, 22, 34],
       [12, 54, 42],
       [56, 67, 99]])

In [63]:
Q15 = Q14.copy()
Q15[[0,1], :] = Q15[[1,0], :]
Q15

array([[12, 54, 42],
       [56, 22, 34],
       [56, 67, 99]])

In [106]:
Q16 = Q15[:, ::-1]
Q16

array([[42, 54, 12],
       [34, 22, 56],
       [99, 67, 56]])

In [112]:
Q17 = np.sort(Q16, axis = 1)
Q17

array([[12, 42, 54],
       [22, 34, 56],
       [56, 67, 99]])

In [114]:
Q18 = np.sort(Q17, axis = 0)
Q18

array([[12, 34, 54],
       [22, 42, 56],
       [56, 67, 99]])

In [109]:
Q19 = np.linspace(1, 200, 100)

In [75]:
Q20 = Q19.reshape(25,4)
Q20

array([[  1.        ,   3.01010101,   5.02020202,   7.03030303],
       [  9.04040404,  11.05050505,  13.06060606,  15.07070707],
       [ 17.08080808,  19.09090909,  21.1010101 ,  23.11111111],
       [ 25.12121212,  27.13131313,  29.14141414,  31.15151515],
       [ 33.16161616,  35.17171717,  37.18181818,  39.19191919],
       [ 41.2020202 ,  43.21212121,  45.22222222,  47.23232323],
       [ 49.24242424,  51.25252525,  53.26262626,  55.27272727],
       [ 57.28282828,  59.29292929,  61.3030303 ,  63.31313131],
       [ 65.32323232,  67.33333333,  69.34343434,  71.35353535],
       [ 73.36363636,  75.37373737,  77.38383838,  79.39393939],
       [ 81.4040404 ,  83.41414141,  85.42424242,  87.43434343],
       [ 89.44444444,  91.45454545,  93.46464646,  95.47474747],
       [ 97.48484848,  99.49494949, 101.50505051, 103.51515152],
       [105.52525253, 107.53535354, 109.54545455, 111.55555556],
       [113.56565657, 115.57575758, 117.58585859, 119.5959596 ],
       [121.60606061, 123

In [77]:
Q21 = Q20[0]

array([1.        , 3.01010101, 5.02020202, 7.03030303])

In [85]:
Q22 = Q20[:,1]
Q22

array([  3.01010101,  11.05050505,  19.09090909,  27.13131313,
        35.17171717,  43.21212121,  51.25252525,  59.29292929,
        67.33333333,  75.37373737,  83.41414141,  91.45454545,
        99.49494949, 107.53535354, 115.57575758, 123.61616162,
       131.65656566, 139.6969697 , 147.73737374, 155.77777778,
       163.81818182, 171.85858586, 179.8989899 , 187.93939394,
       195.97979798])

In [28]:
Q23 = Q20[0:25:2]

In [40]:
Q24 = Q20[[2,4,6]]
Q24

array([[17.08080808, 19.09090909, 21.1010101 , 23.11111111],
       [33.16161616, 35.17171717, 37.18181818, 39.19191919],
       [49.24242424, 51.25252525, 53.26262626, 55.27272727]])

In [93]:
Q25 = Q20.copy()
Q25[Q25<50] = (Q25[Q25 < 50] + 5) *2
Q25

array([[ 12.        ,  16.02020202,  20.04040404,  24.06060606],
       [ 28.08080808,  32.1010101 ,  36.12121212,  40.14141414],
       [ 44.16161616,  48.18181818,  52.2020202 ,  56.22222222],
       [ 60.24242424,  64.26262626,  68.28282828,  72.3030303 ],
       [ 76.32323232,  80.34343434,  84.36363636,  88.38383838],
       [ 92.4040404 ,  96.42424242, 100.44444444, 104.46464646],
       [108.48484848,  51.25252525,  53.26262626,  55.27272727],
       [ 57.28282828,  59.29292929,  61.3030303 ,  63.31313131],
       [ 65.32323232,  67.33333333,  69.34343434,  71.35353535],
       [ 73.36363636,  75.37373737,  77.38383838,  79.39393939],
       [ 81.4040404 ,  83.41414141,  85.42424242,  87.43434343],
       [ 89.44444444,  91.45454545,  93.46464646,  95.47474747],
       [ 97.48484848,  99.49494949, 101.50505051, 103.51515152],
       [105.52525253, 107.53535354, 109.54545455, 111.55555556],
       [113.56565657, 115.57575758, 117.58585859, 119.5959596 ],
       [121.60606061, 123

In [99]:
Q26 = Q20 + Q25
Q26

array([[ 13.        ,  19.03030303,  25.06060606,  31.09090909],
       [ 37.12121212,  43.15151515,  49.18181818,  55.21212121],
       [ 61.24242424,  67.27272727,  73.3030303 ,  79.33333333],
       [ 85.36363636,  91.39393939,  97.42424242, 103.45454545],
       [109.48484848, 115.51515152, 121.54545455, 127.57575758],
       [133.60606061, 139.63636364, 145.66666667, 151.6969697 ],
       [157.72727273, 102.50505051, 106.52525253, 110.54545455],
       [114.56565657, 118.58585859, 122.60606061, 126.62626263],
       [130.64646465, 134.66666667, 138.68686869, 142.70707071],
       [146.72727273, 150.74747475, 154.76767677, 158.78787879],
       [162.80808081, 166.82828283, 170.84848485, 174.86868687],
       [178.88888889, 182.90909091, 186.92929293, 190.94949495],
       [194.96969697, 198.98989899, 203.01010101, 207.03030303],
       [211.05050505, 215.07070707, 219.09090909, 223.11111111],
       [227.13131313, 231.15151515, 235.17171717, 239.19191919],
       [243.21212121, 247

In [101]:
Q27 = np.shape(Q26)

In [102]:
Q28 = Q26.astype(np.int64)
Q28

array([[ 13,  19,  25,  31],
       [ 37,  43,  49,  55],
       [ 61,  67,  73,  79],
       [ 85,  91,  97, 103],
       [109, 115, 121, 127],
       [133, 139, 145, 151],
       [157, 102, 106, 110],
       [114, 118, 122, 126],
       [130, 134, 138, 142],
       [146, 150, 154, 158],
       [162, 166, 170, 174],
       [178, 182, 186, 190],
       [194, 198, 203, 207],
       [211, 215, 219, 223],
       [227, 231, 235, 239],
       [243, 247, 251, 255],
       [259, 263, 267, 271],
       [275, 279, 283, 287],
       [291, 295, 299, 303],
       [307, 311, 315, 319],
       [323, 327, 331, 335],
       [339, 343, 347, 351],
       [355, 359, 363, 367],
       [371, 375, 379, 383],
       [387, 391, 395, 400]])

In [97]:
Q29 = Q28.copy()

arr_slice = Q29[:5, 0]
arr_slice[1] = 42
arr_slice

array([ 13,  42,  61,  85, 109])

In [98]:
data = np.array([2,-4,8,16,-32,-64,128])
data
data[data < 0] = 0
data

array([  2,   0,   8,  16,   0,   0, 128])